In [6]:
 x = NA
 is.na(x)

[1] TRUE

In [7]:
x = c(11, NA, 13, NA)
is.na(x)

[1] FALSE  TRUE FALSE  TRUE

In [9]:
x = c(11,NA,13, NA) # vector
mean(x)
mean(x, na.rm = TRUE)

[1] NA

[1] 12

In [10]:
x = c(11,NA,13,NA)
x

[1] 11 NA 13 NA

In [11]:
which(is.na(x))

[1] 2 4

In [21]:
x = c(11,NA,13,NA)
x

[1] 11 NA 13 NA

In [22]:
sum(is.na(x))

[1] 2

In [23]:
x = c(11,NA,13,NA)
x
complete.cases(x)

[1] 11 NA 13 NA

[1]  TRUE FALSE  TRUE FALSE

In [25]:
x = c(11,NA,13,NA)
x

[1] 11 NA 13 NA

In [26]:
y = na.omit(x)
y

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

In [34]:
x = c(11,NA,13,NA)
y = na.omit(x)
y
mean(x)
mean(y)

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

[1] NA

[1] 12

In [37]:
x = 5
if (x > 4) x * 3
x = 3
if (x > 4) x * 3

[1] 15

In [39]:
x = 5
if (x > 4) {x * 3}

[1] 15

In [40]:
x = 6
if(x > 3){
print("The value is more than 3")
}

[1] "The value is more than 3"

In [41]:
x = 2
if(x > 3){
print("The value is more than 3")
}

In [42]:
x = 5
if ( x==3 ) { x = x-1 } else { x = 2*x }
x

[1] 10

In [43]:
x = 3
if ( x==3 ) { x = x-1 } else { x = 2*x }
x

[1] 2

In [44]:
x = 6
if(x > 3){
print("The value is more than 3")
} else {
print("The value is less than 3")
}

[1] "The value is more than 3"

In [48]:
x = 2
if(x > 3){
print("The value is more than 3")
} else {
print("The value is less than 3")
}

[1] "The value is less than 3"

In [49]:
x = 5
if ( x==3 ) {
x = x-1
} else if ( x < 3 ) {
x = x+5
} else { x = 2*x }
x

[1] 10

In [50]:
x = 2
if ( x==3 ) {
x = x-1
} else if ( x < 3 ) {
x = x+5
} else { x = 2*x }
x

[1] 7

In [51]:
x = 3
if ( x==3 ) {
x = x-1
} else if ( x < 3 ) {
x = x+5
} else { x = 2*x }
x

[1] 2

In [52]:
x = 1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [53]:
x = c(7,9,8,4)
ifelse(x %% 2 == 0,"even number","odd number")

[1] "odd number"  "odd number"  "even number" "even number"

In [54]:
switch(2,"apple", "banana", "orange")

[1] "banana"

In [55]:
switch(1,"apple", "banana", "orange")

[1] "apple"

In [58]:
switch("colour", "colour" = "blue", "gender" = "male", "volume" = 50)

[1] "blue"

In [60]:
switch("volume", "colour" = "blue", "gender" = "male", "volume" = 50)

[1] 50

In [61]:
switch(4,"apple", "banana", "orange")

In [62]:
switch("size", "colour" = "blue", "gender" = "male", "volume" = 50)

In [63]:
x = c(10,15,8,14,6,12)
x

[1] 10 15  8 14  6 12

In [64]:
which(x == 14)
which(x != 12)
which(x > 10)

[1] 4

[1] 1 2 3 4 5

[1] 2 4 6

In [65]:
x = matrix(nrow=3, ncol=3, data=1:9)
x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [66]:
which.min(x) #find which is the minimium valu

[1] 1

In [67]:
which.max(x) #find which is the maximium valu

[1] 9

In [69]:
x = matrix(nrow=3, ncol=3, data=1:9)
x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [70]:
which(x %% 2 == 1)

which(x %% 2 == 1, arr.ind = TRUE)

[1] 1 3 5 7 9

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3