In [3]:
seq()
seq(from = 1, to = 1,
by = ((to - from)/(length.out - 1)),
length.out = NULL, along.with = NULL)

[1] 1

integer(0)

In [4]:
1:10

 [1]  1  2  3  4  5  6  7  8  9 10

In [5]:
10:1

 [1] 10  9  8  7  6  5  4  3  2  1

In [6]:
5:15

 [1]  5  6  7  8  9 10 11 12 13 14 15

In [7]:
-1:-10

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

In [9]:
-10:-1

 [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

In [11]:
-5:-15

 [1]  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15

In [10]:
-15:-5

 [1] -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5

In [12]:
1.23:10

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

In [13]:
1.23:10.54

 [1]  1.23  2.23  3.23  4.23  5.23  6.23  7.23  8.23  9.23 10.23

In [14]:
10.54:2.23

[1] 10.54  9.54  8.54  7.54  6.54  5.54  4.54  3.54  2.54

In [15]:
-1.23:-10

[1] -1.23 -2.23 -3.23 -4.23 -5.23 -6.23 -7.23 -8.23 -9.23

In [16]:
-5.23:6

 [1] -5.23 -4.23 -3.23 -2.23 -1.23 -0.23  0.77  1.77  2.77  3.77  4.77  5.77

In [17]:
seq(10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [18]:
seq(1:10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [19]:
x=2

In [20]:
seq(1, x, x/10)

[1] 1.0 1.2 1.4 1.6 1.8 2.0

In [21]:
x=50

In [22]:
seq(0, x, x/10)

 [1]  0  5 10 15 20 25 30 35 40 45 50

In [23]:
x = seq(1, 50, 1/2)

In [24]:
x

 [1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 14.5 15.0 15.5
[31] 16.0 16.5 17.0 17.5 18.0 18.5 19.0 19.5 20.0 20.5 21.0 21.5 22.0 22.5 23.0
[46] 23.5 24.0 24.5 25.0 25.5 26.0 26.5 27.0 27.5 28.0 28.5 29.0 29.5 30.0 30.5
[61] 31.0 31.5 32.0 32.5 33.0 33.5 34.0 34.5 35.0 35.5 36.0 36.5 37.0 37.5 38.0
[76] 38.5 39.0 39.5 40.0 40.5 41.0 41.5 42.0 42.5 43.0 43.5 44.0 44.5 45.0 45.5
[91] 46.0 46.5 47.0 47.5 48.0 48.5 49.0 49.5 50.0

In [26]:
y=2*x

In [27]:
y

 [1]   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
[20]  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
[39]  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
[58]  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
[77]  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
[96]  97  98  99 100

In [28]:
x = c(9,8,7,6)

In [29]:
ind = seq(along=x)

In [31]:
x[ ind[2] ]

[1] 8

In [32]:
Sys.time()

[1] "2026-08-31 09:08:19 UTC"

In [33]:
Sys.Date()

[1] "2026-08-31"

In [35]:
seq(from = 1, to = 1,
by = ((to - from)/(length.out - 1)),
length.out = NULL, along.with = NULL)

integer(0)

In [37]:
seq(as.Date("2010-01-01"), as.Date("2017-01-01"), by = "years")

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01" "2016-01-01" "2017-01-01"

In [38]:
seq(as.Date("2017-01-01"), by = "days", length = 6)

[1] "2017-01-01" "2017-01-02" "2017-01-03" "2017-01-04" "2017-01-05"
[6] "2017-01-06"

In [ ]:
seq(as.Date("2017-01-01"), by = "months",length = 6)

In [ ]:
seq(as.Date("2017-01-01"), by = "years", length = 6)

In [39]:
startdate = as.Date("2016-1-1")

In [40]:
enddate = as.Date("2017-1-1")

In [41]:
out = seq(enddate, startdate, by = "-1 month")

In [42]:
out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

In [43]:
letters

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [44]:
letters[1:3]

[1] "a" "b" "c"

In [45]:
letters[3:1]

[1] "c" "b" "a"

In [46]:
letters[21:23]

[1] "u" "v" "w"

In [47]:
letters[2]

[1] "b"

In [48]:
LETTERS

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [49]:
LETTERS[1:3]

[1] "A" "B" "C"

In [52]:
LETTERS[3:1]

[1] "C" "B" "A"

In [53]:
LETTERS[21:23]

[1] "U" "V" "W"

In [55]:
LETTERS[21:23]

[1] "U" "V" "W"

In [56]:
rep(3.5, times=10)

 [1] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5

In [57]:
rep(1:4, 2)

[1] 1 2 3 4 1 2 3 4

In [58]:
x = 1:4

In [59]:
x

[1] 1 2 3 4

In [60]:
rep(x, times = 3)

 [1] 1 2 3 4 1 2 3 4 1 2 3 4

In [61]:
rep(x, each = 3)

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

In [63]:
rep(1:4, each = 2)

[1] 1 1 2 2 3 3 4 4

In [64]:
rep(1:4, each = 2, times = 3)

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

In [65]:
rep(1:4, times = 3, each = 2)

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

In [66]:
rep(1:4, 2:5)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

In [67]:
ans = seq(from=2, to=8, by=2)

In [68]:
ans

[1] 2 4 6 8

In [69]:
rep(1:4, ans)

 [1] 1 1 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 4 4

In [70]:
x = matrix(nrow=2, ncol=2, data=1:4, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [71]:
rep(x, 3)

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

In [72]:
rep(c("a", "b", "c"), 2)

[1] "a" "b" "c" "a" "b" "c"

In [73]:
rep(c("apple", "banana", "cake"), 2)

[1] "apple"  "banana" "cake"   "apple"  "banana" "cake"

In [74]:
rep(2, length.out=5)

[1] 2 2 2 2 2

In [75]:
rep(2, length=5)

[1] 2 2 2 2 2

In [76]:
rep(c(2,3), length=5)

[1] 2 3 2 3 2

In [77]:
rep(c(2,3,4), length=5)

[1] 2 3 4 2 3

In [78]:
rep("apple", length=5)

[1] "apple" "apple" "apple" "apple" "apple"

In [79]:
rep(c("a", "b", "c"), length=2)

[1] "a" "b"

In [80]:
rep(c("a", "b", "c"), length=5)

[1] "a" "b" "c" "a" "b"

In [81]:
y = c(8,5,7,6)
y

[1] 8 5 7 6

In [82]:
sort(y)

[1] 5 6 7 8

In [83]:
sort(y, decreasing = TRUE)

[1] 8 7 6 5

In [85]:
y = c(9,8,5,7,6)
y

[1] 9 8 5 7 6

In [86]:
order(y)

[1] 3 5 4 2 1

In [88]:
order(y, decreasing = TRUE)

[1] 1 2 4 5 3

In [89]:
mode(2.432)

[1] "numeric"

In [90]:
mode(c(3,4,5,6,7,8))

[1] "numeric"

In [91]:
mode("India")

[1] "character"

In [92]:
mode(c("India", "CANADA"))

[1] "character"

In [93]:
mode(factor(c("UP", "MP")) )

[1] "numeric"

In [94]:
mode(list("India", "USA"))

[1] "list"

In [95]:
mode(data.frame(x=1:2, y=c("India", "USA")))

[1] "list"

In [96]:
mode(data.frame(x=1:2, y=c("India", "USA")))

[1] "list"

In [97]:
mode(print)

[1] "function"

In [98]:
x1 = matrix(nrow=2, ncol=2, data=1:4, byrow=T)

In [99]:
x1

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [100]:
x2 = matrix(nrow=2, ncol=2, data=5:8, byrow=T)

In [101]:
x2

     [,1] [,2]
[1,] 5    6
[2,] 7    8

In [102]:
x1+x2

     [,1] [,2]
[1,]  6    8
[2,] 10   12

In [103]:
x1[2,1] = "hello"

In [104]:
x1

     [,1]  [,2]
[1,] 1     2
[2,] hello 4

In [105]:
x1 + x2

ERROR: Error in x1 + x2: non-numeric argument to binary operator

In [106]:
x1 = matrix(nrow=2, ncol=2, data=1:4, byrow=T)

In [107]:
x1

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [108]:
x2 = matrix(nrow=2, ncol=2, data=5:8, byrow=T)

In [109]:
x2

     [,1] [,2]
[1,] 5    6
[2,] 7    8

In [110]:
matlist = list(x1, x2)

In [111]:
matlist

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [112]:
matlist[1]

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

In [113]:
matlist[2]

[[1]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [114]:
z1 = list( c("water", "juice", "lemonade"),
rep(1:4, each=2), matrix(data=5:8, nrow=2,
ncol=2, byrow=T) )

In [121]:
z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [116]:
z1[[1]]

[1] "water"    "juice"    "lemonade"

In [117]:
z1[1][2]

[[1]]
NULL

In [118]:
z1[[1]][2]

[1] "juice"